package com.pilinhas.android.ui

import androidx.compose.ui.graphics.Color

internal object Color {
    object Light {
        val surfaceTint = Color(0xFF6750A4)
        val onErrorContainer = Color(0xFF410E0B)
        val onError = Color(0xFFFFFFFF)
        val errorContainer = Color(0xFFF9DEDC)
        val onTertiaryContainer = Color(0xFF31111D)
        val onTertiary = Color(0xFFFFFFFF)
        val tertiaryContainer = Color(0xFFFFD8E4)
        val tertiary = Color(0xFF7D5260)
        val error = Color(0xFFB3261E)
        val outline = Color(0xFF79747E)
        val onBackground = Color(0xFF1C1B1F)
        val background = Color(0xFFFFFBFE)
        val inverseOnSurface = Color(0xFFF4EFF4)
        val inverseSurface = Color(0xFF313033)
        val onSurfaceVariant = Color(0xFF49454F)
        val onSurface = Color(0xFF1C1B1F)
        val surfaceVariant = Color(0xFFE7E0EC)
        val surface = Color(0xFFFFFBFE)
        val onSecondaryContainer = Color(0xFF1D192B)
        val onSecondary = Color(0xFFFFFFFF)
        val secondaryContainer = Color(0xFFE8DEF8)
        val secondary = Color(0xFF625B71)
        val inversePrimary = Color(0xFFD0BCFF)
        val onPrimaryContainer = Color(0xFF21005D)
        val onPrimary = Color(0xFFFFFFFF)
        val primaryContainer = Color(0xFFEADDFF)
        val primary = Color(0xFF6750A4)
    }

    object Dark {
        val surfaceTint = Color(0xFFD0BCFF)
        val onErrorContainer = Color(0xFFF2B8B5)
        val onError = Color(0xFF601410)
        val errorContainer = Color(0xFF8C1D18)
        val onTertiaryContainer = Color(0xFFFFD8E4)
        val onTertiary = Color(0xFF492532)
        val tertiaryContainer = Color(0xFF633B48)
        val tertiary = Color(0xFFEFB8C8)
        val error = Color(0xFFF2B8B5)
        val outline = Color(0xFF938F99)
        val onBackground = Color(0xFFE6E1E5)
        val background = Color(0xFF1C1B1F)
        val inverseOnSurface = Color(0xFF313033)
        val inverseSurface = Color(0xFFE6E1E5)
        val onSurfaceVariant = Color(0xFFCAC4D0)
        val onSurface = Color(0xFFE6E1E5)
        val surfaceVariant = Color(0xFF49454F)
        val surface = Color(0xFF1C1B1F)
        val onSecondaryContainer = Color(0xFFE8DEF8)
        val onSecondary = Color(0xFF332D41)
        val secondaryContainer = Color(0xFF4A4458)
        val secondary = Color(0xFFCCC2DC)
        val inversePrimary = Color(0xFF6750A4)
        val onPrimaryContainer = Color(0xFFEADDFF)
        val onPrimary = Color(0xFF381E72)
        val primaryContainer = Color(0xFF4F378B)
        val primary = Color(0xFFD0BCFF)
    }
}